export const VgRankMap = new Map([
    ['-1', {rank: 'Unranked', color: '', url: ''}],
    ['0', {rank: 'Just Beginning', color: 'Bronze', url: ''}],
    ['1', {rank: 'Just Beginning', color: 'Silver', url: ''}],
    ['2', {rank: 'Just Beginning', color: 'Gold', url: ''}],
    ['3', {rank: 'Getting there', color: 'Bronze', url: ''}],
    ['4', {rank: 'Getting there', color: 'Silver', url: ''}],
    ['5', {rank: 'Getting there', color: 'Gold', url: ''}],
    ['6', {rank: 'Rock Solid', color: 'Bronze', url: ''}],
    ['7', {rank: 'Rock Solid', color: 'Silver', url: ''}],
    ['8', {rank: 'Rock Solid', color: 'Gold', url: ''}],
    ['9', {rank: 'Worthy foe', color: 'Bronze', url: ''}],
    ['10', {rank: 'Worthy foe', color: 'Silver', url: ''}],
    ['11', {rank: 'Worthy foe', color: 'Gold', url: ''}],
    ['12', {rank: 'Got Swagger', color: 'Bronze', url: ''}],
    ['13', {rank: 'Got Swagger', color: 'Silver', url: ''}],
    ['14', {rank: 'Got Swagger', color: 'Gold', url: ''}],
    ['15', {rank: 'Credible threat', color: 'Bronze', url: ''}],
    ['16', {rank: 'Credible threat', color: 'Silver', url: ''}],
    ['17', {rank: 'Credible threat', color: 'Gold', url: ''}],
    ['18', {rank: 'The Hotness', color: 'Bronze', url: ''}],
    ['19', {rank: 'The Hotness', color: 'Silver', url: ''}],
    ['20', {rank: 'The Hotness', color: 'Gold', url: ''}],
    ['21', {rank: 'Simply Amazing', color: 'Bronze', url: ''}],
    ['22', {rank: 'Simply Amazing', color: 'Silver', url: ''}],
    ['23', {rank: 'Simply Amazing', color: 'Gold', url: ''}],
    ['24', {rank: 'Pinnacle of Awesome', color: 'Bronze', url: ''}],
    ['25', {rank: 'Pinnacle of Awesome', color: 'Silver', url: ''}],
    ['26', {rank: 'Pinnacle of Awesome', color: 'Gold', url: ''}],
    ['27', {rank: 'Vainglorious', color: 'Bronze', url: ''}],
    ['28', {rank: 'Vainglorious', color: 'Silver', url: ''}],
    ['29', {rank: 'Vainglorious', color: 'Gold', url: ''}],
]);